Exception in thread Thread-2 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-15 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-28 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-41 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-54 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-67 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-80 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-93 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-106 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-119 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
Exception in thread Thread-132 (get_throughput):
Traceback (most recent call last):
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shaya\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shaya\OneDrive\Desktop\Chaos-Scenario\chat-system\mongo-con-ovl.py", line 74, in get_throughput
    db.set_profiling_level(pymongo.ProfilingLevel.ALL)
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymongo' has no attribute 'ProfilingLevel'
